#! /bin/bash

main(){
    while true
    do
        read -p 'Please enter new ssh port(default:22):' ssh_port
        [ -z $ssh_port ] && ssh_port=22 && break
        [ $ssh_port -ge 1 -a $ssh_port -le 65535 ] 2>/dev/null && break
        echo Port number must be in the range from 1 to 65535!
    done
    read -p 'Please enter public key:' key
    sudo su <<-EOSU
	sed -i "/^#\?Port/s/.*/Port $ssh_port/" /etc/ssh/sshd_config
	service ssh restart
	mkdir -p ~/.ssh
	cat >> ~/.ssh/authorized_keys <<-EOF
	$key
	EOF
	EOSU
}

main
