#! /bin/bash

setupTimezone() {
    ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    dpkg-reconfigure -f noninteractive tzdata
}

setupSysctl() {
    cat >/etc/sysctl.d/90-bbr-sysctl.conf <<-EOF
	net.core.default_qdisc=fq
	net.ipv4.tcp_congestion_control=bbr
	EOF
}

setupBash() {
    if ! $(grep -q HISTCONTROL ~/.bashrc); then
        cat >>~/.bashrc <<-EOF

		# don't put duplicate lines or lines starting with space in the history.
		# See bash(1) for more options
		HISTCONTROL=ignoreboth
		EOF
    fi
}

installNftables() {
    apt -qq update
    apt -qq -y install nftables ntp
    systemctl enable nftables
    service nftables start
}

main() {
    setupTimezone
    setupSysctl
    setupBash
    installNftables
}

main
