#! /bin/bash

installSoftware(){
    cat >> /etc/apt/sources.list.d/nginx.list <<-EOF
	deb http://packages.amplify.nginx.com/debian/ $(lsb_release -sc) amplify-agent
	EOF
    curl http://nginx.org/keys/nginx_signing.key|apt-key add -
    apt -qq update
    apt -qq -y install nginx nginx-amplify-agent
}

setupAmplify(){
    sed "s/api_key.*$/api_key = $api_key/" /etc/amplify-agent/agent.conf.default > /etc/amplify-agent/agent.conf
    #sed -i 's/mysql = False/mysql = True/' /etc/amplify-agent/agent.conf
    cat > /etc/nginx/conf.d/nginx_amplify.conf <<-EOF
	server {
	    server_name 127.0.0.1;
	    location /nginx_status {
	        stub_status on;
	        allow 127.0.0.1;
	        deny all;
	        access_log off;
	    }
	}
	EOF
}

main(){
    read -p 'Please enter your amplify api key:' api_key
    installSoftware >/dev/null 2>&1
    setupAmplify
}

main
