#! /bin/bash

installSoftware() {
    apt -qq update
    apt -qq -y install nginx
    rm /etc/nginx/sites-enabled/default
    curl -Lo amplify-agent.deb http://packages.amplify.nginx.com/debian/pool/amplify-agent/n/nginx-amplify-agent/nginx-amplify-agent_1.7.0-5~buster_amd64.deb
    dpkg -i amplify-agent.deb && rm amplify-agent.deb
}

setupAmplify() {
    sed "s/api_key.*$/api_key = $api_key/" /etc/amplify-agent/agent.conf.default > /etc/amplify-agent/agent.conf
    #sed -i 's/mysql = False/mysql = True/' /etc/amplify-agent/agent.conf
    cat > /etc/nginx/conf.d/nginx_amplify.conf <<-EOF
	server {
	    server_name 127.0.0.1;
	    location /nginx_status {
	        stub_status on;
	        allow 127.0.0.1;
	        deny all;
	        access_log off;
	    }
	}
	EOF
}

main() {
    read -p 'Please enter your amplify api key:' api_key
    installSoftware
    setupAmplify
    echo Please copy nginx conf files
}

main
