#! /bin/bash

installSoftware() {
    apt -qq -y install chasquid
    mkdir -p /etc/chasquid/certs/mx.$domain
    mv /etc/chasquid/chasquid.conf /etc/chasquid/chasquid.conf.default
    cat > /etc/chasquid/chasquid.conf <<-EOF
	hostname: "mx.$domain"
	mail_log_path: "/var/log/chasquid/mail.log"
	EOF
    sed -i '\|^ExecStart=|s|$| -logfile /var/log/chasquid/chasquid.log|' /usr/lib/systemd/system/chasquid.service
    systemctl daemon-reload
    mkdir -p /var/log/chasquid
    chown -R chasquid:chasquid /var/log/chasquid
    cat >/etc/logrotate.d/chasquid <<-EOF
	/var/log/chasquid/*.log {
	    copytruncate
	    rotate 12
	    weekly
	    compress
	    delaycompress
	    missingok
	    notifempty
	}
	EOF
}

main() {
    read -p 'Please enter domain:' domain
    installSoftware
    echo Please link cert files and add user(chasquid-util user-add)
}

main
