#! /bin/bash
#SSH Debian NGINX MongoDB

setupSSH() {
    sed -i "/^#\?Port/s/.*/Port $ssh_port/" /etc/ssh/sshd_config
    sed -i "/^PermitRootLogin/s/./#&/" /etc/ssh/sshd_config
    service ssh restart
}

setupTimezone() {
    ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    dpkg-reconfigure -f noninteractive tzdata
}

prepareInstall() {
    apt -qq update
    apt -qq -y install curl

    echo "deb [signed-by=/usr/share/keyrings/mongodb-8.0.gpg] http://repo.mongodb.org/apt/debian $(lsb_release -sc)/mongodb-org/8.0 main" | tee -a /etc/apt/sources.list.d/software.list > /dev/null
    curl https://pgp.mongodb.com/server-8.0.asc | gpg -o /usr/share/keyrings/mongodb-8.0.gpg --dearmor
}

installSoftware() {
    apt -qq update
    apt -qq -y install nginx nftables ntp
    systemctl enable nftables
    rm /etc/nginx/sites-enabled/default
}

writeConfig() {
    #System
    cat >/etc/sysctl.d/90-bbr-sysctl.conf <<-EOF
	net.core.default_qdisc=fq
	net.ipv4.tcp_congestion_control=bbr
	EOF

    if ! $(grep -q HISTCONTROL ~/.bashrc); then
        cat >>~/.bashrc <<-EOF

		# don't put duplicate lines or lines starting with space in the history.
		# See bash(1) for more options
		HISTCONTROL=ignoreboth
		EOF
    fi
}

main() {
    STARTTIME=$(date +%s.%N)
    setupSSH
    setupTimezone
    prepareInstall
    installSoftware
    writeConfig
    ENDTIME=$(date +%s.%N)
    echo All done! Duration for process: $(python -c "print(round(${ENDTIME}-${STARTTIME},3))") seconds
}

main
