#! /bin/bash

main() {
    read -p 'Please enter username:' username
    read -p 'Please enter password:' password
    read -p 'Please enter exit-server:' server
    brew install geph
    cat > ~/Library/LaunchAgents/geph.plist <<-EOF
	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
	<plist version="1.0">
	  <dict>
	    <key>RunAtLoad</key>
	    <true/>
	    <key>Label</key>
	    <string>geph</string>
	    <key>ProgramArguments</key>
	    <array>
	      <string>/usr/local/bin/geph4-client</string>
	      <string>connect</string>
	      <string>--username</string>
	      <string>$username</string>
	      <string>--password</string>
	      <string>$password</string>
	      <string>--exit-server</string>
	      <string>$server</string>
	    </array>
	  </dict>
	</plist>
	EOF
    launchctl bootstrap gui/$(id -u) ~/Library/LaunchAgents/geph.plist
}

main
