name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Build
        run: |
          cd windows
          GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" UpdateGeph.go
          GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" UpdateV2Ray.go

      - name: Delete Old Release
        uses: actions/github-script@v3
        with:
          script: |
            let release
            try {
              release = await github.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: 'v1.0'
              })
            } catch(e) {
              console.error(e)
              return
            }

            await github.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id
            })

            await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/v1.0'
            })

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(TZ=CST date +'%Y-%m-%d')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0
          release_name: ${{ steps.date.outputs.date }}
          body: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false

      - name: Upload Release Asset1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows/UpdateGeph.exe
          asset_name: UpdateGeph.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload Release Asset2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows/UpdateV2Ray.exe
          asset_name: UpdateV2Ray.exe
          asset_content_type: application/vnd.microsoft.portable-executable
